python prune.py \
--config celeba.yml \
--exp run/ddim_celeba_pruning_reinit \
--timesteps 100 \
--eta 0 \
--ni \
--doc post_training \
--skip_type quad  \
--pruning_ratio 0.3 \
--use_ema \
--use_pretrained \
--pruner reinit \
--taylor_batch_size 96 \