python finetune_simple.py \
--config celeba.yml \
--timesteps 100 \
--eta 0 \
--ni \
--exp run/finetune_simple/celeba_ours_T=$1.pth \
--doc post_training \
--skip_type uniform  \
--pruning_ratio 0.3 \
--use_ema \
--use_pretrained \
--thr $1 \
--pruner ours \
--taylor_batch_size 64